# Generated by Django 4.2.2 on 2023-06-27 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=155, verbose_name='Электронная почта')),
                ('country', models.CharField(max_length=155, verbose_name='Страна')),
                ('city', models.CharField(max_length=155, verbose_name='Город')),
                ('street', models.CharField(max_length=155, verbose_name='Улица')),
                ('building_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер здания')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Название')),
                ('model', models.PositiveSmallIntegerField(verbose_name='Модель')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, unique=True, verbose_name='Название')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], default=0, verbose_name='Уровень')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Задолженность перед поставщиком')),
                ('at_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chain_store.contact', verbose_name='Контакты')),
                ('products', models.ManyToManyField(blank=True, related_name='products', to='chain_store.product', verbose_name='Продукт')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_provider', to='chain_store.provider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Объект сети',
                'verbose_name_plural': 'Объекты сети',
            },
        ),
    ]
