# Generated by Django 4.2.2 on 2023-06-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], default=0, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='store',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Задолженность перед поставщиком'),
        ),
    ]
