# Generated by Django 4.2.2 on 2023-06-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_store', '0003_contact_remove_product_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='chain_store.product', verbose_name='Продукт'),
        ),
    ]
