# Generated by Django 4.2.2 on 2023-06-26 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chain_store', '0004_alter_store_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chain_store.contact', verbose_name='Контакты'),
        ),
    ]
